### ISSUE TITLE
Updated existing project and Clearscript broke

### ISSUE THREAD

**Issue by rushfrisby** [eswann/ClearScript.Manager#3]
When I create a new ScopeManager I get this exception:

```
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args) in c:\Projects\ClearScript\ClearScript-5_4_1\ClearScript\V8\V8Proxy.cs:line 93
   at Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, Boolean enableDebugging, Int32 debugPort) in c:\Projects\ClearScript\ClearScript-5_4_1\ClearScript\V8\V8IsolateProxy.cs:line 70
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort) in c:\Projects\ClearScript\ClearScript-5_4_1\ClearScript\V8\V8Runtime.cs:line 204
   at ClearScript.Manager.RuntimeManager..ctor(IManagerSettings settings) in C:\Projects\ClearScript\ClearScript.Manager\src\ClearScript.Manager\RuntimeManager.cs:line 135
   at ClearScript.Manager.ManagerPool.GetRuntime() in C:\Projects\ClearScript\ClearScript.Manager\src\ClearScript.Manager\ManagerPool.cs:line 78
   at ClearScript.Manager.ManagerScope..ctor() in C:\Projects\ClearScript\ClearScript.Manager\src\ClearScript.Manager\ManagerScope.cs:line 17
   at BlackMamba.Logic.ClearScriptRuleEngine.Execute(RuleEngineExecutionPlan plan) in c:\Rush\dev\BlackMamba\BlackMamba.Logic\ClearScriptRuleEngine.cs:line 55
   at BlackMamba.Logic.RuleEngineManager.<>c__DisplayClass4.<Execute>b__2() in c:\Rush\dev\BlackMamba\BlackMamba.Logic\RuleEngineManager.cs:line 69
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
   
And the inner exception:

```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at V8Isolate.Create(StdString* , V8IsolateConstraints* , Boolean , Int32 )
   at Microsoft.ClearScript.V8.V8IsolateProxyImpl..ctor(String gcName, V8RuntimeConstraints gcConstraints, Boolean enableDebugging, Int32 debugPort) in c:\projects\clearscript\clearscript-5_4_1\clearscript\v8\clearscriptv8\v8isolateproxyimpl.cpp:line 86
```

I upgraded Clearscript Manager and Clearscript from an older version to latest and this started happening with no other code changes. It looks like it just has something to do with Clearscript and not Clearscript Manager... I'm just not sure what. From a new project I can use Clearscript Manager and the same exact code just fine but in my existing project I get this exception. Any ideas?

**Comment by rushfrisby** [comment]
Actually maybe it does have something to do with ClearScript Manager... in the RuntimeManager constructor a V8Runtime is being constructed with V8RuntimeConstraints. I just read that because of changed in V8 that it is recommended to use the empty constructor for V8Runtime. See https://clearscript.codeplex.com/discussions/572036

**Comment by eswann** [comment]
Thanks, will take a look....how about a pull request?

**Comment by rushfrisby** [comment]
I got it working with the empty constructor. I ended up completely removing the 3 properties that were used to construct V8RuntimeConstraints since they were not used anywhere else. Is this okay or did you want to keep them around for something else?

**Comment by eswann** [comment]
OK, will take a look today.

**Comment by eswann** [comment]
Set the default byte parameters to be 0, can still be overridden in config.  Version 1.3.5
